import streamlit as st


st.write("""
# Todays Cyrptocurrency prices
""")
         



crypto_symbol = st.selectbox(
    "Choose a cyrptocurrency:",
    [
    'BTC',
    'ETH',
    'USDT',
    'XRP',
    'BNB',
    'USDC',
    'SOL',
    'TRX',
    'DOGE',
    'HYPE',
    'LEO',
    'BCH',
    'ADA',
    'XMR',
    'LINK',
    'ZEC',
    'CC',
    'XLM',
    'DAI',
    'M',
    'USD1',
    'LTC',
    'AVAX',
    'HBAR',
    'USDe',
    'SUI',
    'SHIB',
    'PYUSD',
    'TON',
    'CRO',
    'TAO',
    'XAUt',
    'USDG',
    'WLFI',
    'PAXG',
    'MNT',
    'SKY',
    'UNI',
    'DOT',
    'PI',
    'NEAR',
    'OKB',
    'ASTER',
    'PEPE',
    'RLUSD',
    'AAVE',
    'USDD',
    'BGB',
    'ICP',
    'ETC',
    'ONDO',
    'DEXE',
    'KCS',
    'U',
    'ALGO',
    'ATOM',
    'POL',
    'ENA',
    'RENDER',
    'KAS',
    'MORPHO',
    'QNT',
    'WLD',
    'GT',
    'STABLE',
    'APT',
    'ARB',
    'FIL',
    'JST',
    'JUP',
    'FLR',
    'PENGU',
    'VET',
    'XDC',
    'TRUMP',
    'PUMP',
    'NEXO',
    'NIGHT',
    'BONK',
    'CHZ',
    'SIREN',
    'TUSD',
    'CAKE',
    'ZRO',
    'FET',
    'EDGE',
    'VIRTUAL',
    'DASH',
    'EURC',
    'AERO',
    'SEI',
    'FDUSD',
    'VVV',
    'STX',
    'XTZ',
    'H',
    'ZBCN',
    '币安人生',
    'LUNC',
    'ETHFI',
    'MON',
    'INJ',
    'SUN',
    'SPX',
    'CRV',
    'LDO',
    'IMX',
    'GNO',
    'DCR',
    'TIA',
    'NFT',
    'BTT',
    'BSV',
    'CFX',
    'FLOKI',
    'KAIA',
    '2Z',
    'JASMY',
    'SYRUP',
    'PYTH',
    'KITE',
    'GRT',
    'OP',
    'IOTA',
    'AXS',
    'ENS',
    'XCN',
    'COMP',
    'SAND',
    'RAVE',
    'STRK',
    'PENDLE',
    'LIT',
    'THETA',
    'TEL',
    'NEO',
    'RAY',
    'FARTCOIN',
    'GENIUS',
    'SFP',
    'TWT',
    'HNT',
    'MANA',
    'IP',
    'VSN',
    'WIF',
    'XPL',
    'RUNE',
    'CVX',
    'WAL',
    'SKYAI',
    'MX',
    'JTO',
    'GALA',
    'BAT',
    'AB',
    'FF',
    'TRAC',
    'DEEP',
    'CHIP',
    'ZK',
    'A',
    'STG',
    'XEC',
    'AKT',
    'B',
    'GLM',
    'BEAT',
    '1INCH',
    'FLUID',
    'RIVER',
    'DYDX',
    'SENT',
    'S',
    'EGLD',
    'AR',
    'EIGEN',
    'ENJ',
    '0G',
    'CFG',
    'ATH',
    'RSR',
    'MELANIA',
    'CHEEMS',
    'WEMIX',
    'SNX',
    'AWE',
    'GAS',
    'ZEN',
    'APE',
    'LPT',
    'COW',
    'SAFE',
    'KAITO',
    'BEAM',
    'YFI',
    'FTT',
    'ZRX',
    'RVN',
    'SPK',
    ]
)
def get_todays_crypto_prices(symbol):
    # Here is where we get Crypto prices for free from Alpaca
    # Query strings look like this:   ?key1=value1&key2=value2&key3=value3
    # We are not using urllib because we have only simple needs here.
    url = f"https://data.alpaca.markets/v1beta3/crypto/us/bars?symbols={symbol}%2FUSD&timeframe=1Min&limit=1000&sort=asc"
    headers = {"accept": "application/json"}

    # Send the request
    response = requests.get(url, headers=headers)

    # Lift out the rows of prices and convert to a table
    df = pd.DataFrame(response.json()['bars'][f'{symbol}/USD'])

    # Convert time into datetime type
    df['t'] = pd.to_datetime(df['t'])

    # Rename columns to readable names with correct meanings
    df = df.rename(columns={
        't': 'Time', 'o': 'Open', 'h': 'High', 'l': 'Low', 'c': 'Close',
        'v': 'Volume', 'n': 'Count', 'vw': 'VWAP'
    })

    # Reorder the columns more naturally
    df = df[['Time','Open','Close','High','Low','Volume','Count','VWAP']]

    # Round to two decimals, as USD should be rounded
    df[['Open','Close','High','Low','VWAP']] = df[['Open','Close','High','Low','VWAP']].round(2)

    return df

st.write(get_todays_crypto_prices(crypto_symbol))